---
title: "precipation-streams-wells"
author: "Rebstock"
date: "6/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE, echo=FALSE}

library(tidyverse)
library(readxl)
library(x12)

library(urbnmapr)
library(rworldmap)
library(sp)
library(sf)

library(maps) 
library(dplyr) 
library(ggplot2)

```

```{r}

## pulling in data for streams in Floyd 
locations_features_floyd_county <- read_excel("~/Desktop/Virginia-Tech/DSPG-2021/Floyd-County/DSPG_Floyd/data/locations-features-floyd-county.xlsx")
## chaning column names 
colnames(locations_features_floyd_county) <- locations_features_floyd_county[1,]

## only want certain columns and rows 

locations_features_floyd_county <- data.frame(locations_features_floyd_county[-c(1, 10,15:19),-c(2,4,6,8,10,11)])


## replacing the degree sign and N and W 
locations_features_floyd <- locations_features_floyd_county%>% 
  mutate(Latitude1 = str_replace_all(Latitude, "°", ""), Longitude1 = str_replace_all(Longitude, "°", "")
) %>%
  select(Feature.Name,Type,Latitude1, Longitude1)


locations_features_floyd <- locations_features_floyd%>% 
  mutate(Latitude = str_replace_all(Latitude1, "N", ""), Longitude = str_replace_all(Longitude1, "W", "")
) %>%
  select(Feature.Name,Type,Latitude, Longitude)

## need to change the Longitude and Latitude columns to numeric 
locations_features_floyd$Latitude <- as.numeric(locations_features_floyd$Latitude) 
locations_features_floyd$Longitude <- as.numeric(locations_features_floyd$Longitude) 

## need to multiply the Longitude by -1 since it is W 
locations_features_floyd <- locations_features_floyd%>% 
  mutate(Longitude1 = -1*Longitude
) %>%
  select(Feature.Name,Type, Latitude, Longitude1)

## getting county data for just floyd 
floyd <- left_join(countydata, counties, by = "county_fips") %>% 
  filter(state_name %in% c("Virginia"), county_name %in% c("Floyd County")) 

## creating map for the streams in Floyd County 
floyd %>%
  ggplot(aes(long, lat, group = 1)) +
  geom_polygon( size = 0.05, fill = "grey") +
  coord_map(projection = "albers", lat0 = 39, lat1 = 45) +
  geom_point(data=locations_features_floyd, aes(x=Longitude1, y=Latitude), color = "gold", alpha = .6, size = 5) + 
  theme(
  plot.title = element_text(color = "black", size = 12, face = "bold"),
  plot.subtitle = element_text(color = "blue", size = 7),
  plot.caption = element_text(color = "black", face = "italic", size = 7)
) + 
  labs(title = "Streams Located in Floyd County",
       caption = "Data Source: https://www.topoquest.com/place-detail.php?id=2390186",
       subtitle = "*Most of these streams flow into the Town of Floyd which is why they are centered around the same area.")

```


```{r}

##wells

wells <- data.frame(t(read_excel("~/Desktop/Virginia-Tech/DSPG-2021/Floyd-County/DSPG_Floyd/data/NRV-wells-floyd-county-2011.xlsx", col_types = "numeric"))  ) 
colnames(wells) = c("Number_Wells", "Well_Depth", "Casing_Depth" , "Diameter", "Withdrawl_MGD", "Withdrawl_GPD", "Max_MGD", "Max_GPD", "Permitted")
wells <- wells[-1,]
wells$Names <- c("Christie", "Shortt", "Howard", "Rec.Park", "Comm. Cntr")

wells %>% 
  ggplot(aes(x = Names, y = Withdrawl_GPD, fill = Names)) + 
  geom_bar(stat = "identity", position = "dodge")+ 
  labs(title = "Average Daily Withdrawals of Public Wells", 
       caption = "Data Source: New River Valley Water Supply Plan 2011", 
       subtitle = "*Note this data is from 2011 so the average daily withdrawal may be different now. ",
       x = "Wells",
       y = "Withdrawal (GPD) ") + theme(legend.position = "none", 
                                        plot.subtitle = element_text(color = "blue", size = 9), plot.caption = element_text(color = "black", face = "italic", size = 7))

## above is a bar plot of the daily withdrawals from each well
wells$Percent <- wells$Withdrawl_GPD/wells$Max_GPD

## plotting the percent usage of each well and the well depth to see if there is a correlation 
p <- ggplot(wells, aes(x = Names)) + 
geom_col(aes(y = Percent), fill = "white", color = "red")  + 
geom_line(aes(y = Well_Depth/1000), color = "blue", size = 1, group = 1) +
scale_y_continuous("Percent", sec.axis = sec_axis(~.*1000, name = "Depth (ft)"))  + 
  labs(title = "Percent of Usage and Well Depth of Wells in Floyd County",
       caption = "Data Source: New River Valley Water Supply Plan 2011",
       subtitle = "*could be a potential correlation of well depth compared to the average daily withdrawal amount",x = "Wells") + theme(plot.subtitle = element_text(color = "blue", size = 7), 
        plot.caption = element_text(color = "black", face = "italic", size = 7),)


p

``` 

```{r}


climate <- data.frame(read_excel("~/Desktop/Virginia-Tech/DSPG-2021/Floyd-County/DSPG_Floyd/data/climate-floyd-county-usClimateData.xlsx")) 

## Average Rainfall in Floyd 
gc <- ggplot(climate, aes(x = Month, y = Rainfall, fill = Month)) +
  geom_bar(stat = "identity") + 
  scale_x_discrete(limits = month.abb) +
  labs(x = "Month", 
       y = "Rainfall (in)", 
       title = "Average Rainfall in Floyd County",
       caption = "Data Source: US Climate Data",
       subtitle = "*This data is the average of each month from 1980-2010") + theme(legend.position = "none", 
                                                                                    plot.subtitle = element_text(size = 9, color = "blue"))
gc

## monthly rainfall for 3 surrounding counties 
rainfall <- ggplot(climate, aes(fill = County, x = Month, y = Rainfall)) + 
  geom_bar(position="dodge", stat="identity") + 
  scale_x_discrete(limits = month.abb)+ 
  labs(title = "Average Monthly Ranfall from 3 surrounding counties in Virginia",
       caption = "Data Source: US Climate Data",
       subtitle = "*This can be used to see how Floyd County comapres to its surrounding counties based on groundwater.", 
       y="Rainfall (in)")+ theme( 
                                                                                    plot.subtitle = element_text(size = 9, color = "blue"))

rainfall
## monthly max temps for 3 surrounding counties 
max_temp <- ggplot(climate, aes(fill = County, x = Month, y = Max_Temp)) + 
  geom_bar(position="dodge", stat="identity") + 
  scale_x_discrete(limits = month.abb) + 
  labs(title = "Maximum Tempature from 3 surrounding counties in Virginia",
       caption = "Data Source: US Climate Data",
       subtitle = "*This can be used to see how Floyd County comapres to its surrounding counties based on if the groundwater is getting evaporated",
       y = "Temperature (F) ")+ theme( 
                                                                                    plot.subtitle = element_text(size = 7, color = "blue"))

max_temp

## monthly min temps for 3 surrounding counties 
min_temp <- ggplot(climate, aes(fill = County, x = Month, y = Min_Temp)) + 
  geom_bar(position="dodge", stat="identity") + 
  scale_x_discrete(limits = month.abb) +
   labs(title = "Minimum Tempature from 3 surrounding counties in Virginia",
       caption = "Data Source: US Climate Data",
       subtitle = "*This can be used to see how Floyd County comapres to its surrounding counties based on if the groundwater freezes and melts during the Winter",
       y = "Temperature (F)") + theme( 
                                                                                    plot.subtitle = element_text(size = 6, color = "blue"))

min_temp
```


